### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:3306

### ISSUE THREAD

**Issue by SandFoxy** [Jasmisek/cloud-configs#1]
connect ECONNREFUSED 127.0.0.1:3306

**Comment by Jasmisek** [comment]
I cannot help when you only tell me that the connection refused and I don't have any details if password is incorrect etc.
Please reply with more details for further assistance.

**Comment by Jasmisek** [comment]
I just found out the issue should be fixed with the new pull request.
